ctf_loader: Plug leak when bailing out due to unknown tag
Fixes this coverity report:

  Error: RESOURCE_LEAK (CWE-772): [#def6]
  dwarves-1.13/ctf_loader.c:458: alloc_fn: Storage is returned from allocation function "zalloc".
  dwarves-1.13/ctf_loader.c:458: var_assign: Assigning: "tag" = storage returned from "zalloc(40UL)".
  dwarves-1.13/ctf_loader.c:470: leaked_storage: Variable "tag" going out of scope leaks the storage it points to.
  #  468|   	default:
  #  469|   		printf("%s: FOO %d\n\n", __func__, type);
  #  470|-> 		return 0;
  #  471|   	}
  #  472|

Reported-by: William Cohen <wcohen@redhat.com>
Fixes: 2dfa5fe6eab0 ("[DWARVES]: Initial CTF support")
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>