reorganize: Ditch unused variable
Addressing this compiler warning:

  [ 56%] Building C object CMakeFiles/dwarves_reorganize.dir/dwarves_reorganize.c.o
  /home/acme/git/pahole/dwarves_reorganize.c: In function ‘class__move_bit_member’:
  /home/acme/git/pahole/dwarves_reorganize.c:356:16: error: unused variable ‘is_last_member’ [-Werror=unused-variable]
    const uint8_t is_last_member = (from->tag.node.next ==

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>