MANIFEST: Add lib/include/bpf
The tarball wasn't working without this file:

  [ 32%] Building C object CMakeFiles/dwarves.dir/btf_encoder.c.o
  /tmp/dwarves-1.22/btf_encoder.c:18:10: fatal error: bpf/btf.h: No such file or directory
   #include <bpf/btf.h>
            ^~~~~~~~~~~
  compilation terminated.

Cc: Luca Boccassi <bluca@debian.org>
Fixes: 82756ea3eaf1f6e7 ("libbpf: Fixup patch to allow to use packaged version")
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>