btf_encoder: Normalize array index type for parallel dwarf loading case
With latest llvm15 built kernel (make -j LLVM=1), I hit the following
error when build selftests (make -C tools/testing/selftests/bpf -j LLVM=1):
  In file included from skeleton/pid_iter.bpf.c:3:
  .../selftests/bpf/tools/build/bpftool/vmlinux.h:84050:9: error: unknown type name
       '__builtin_va_list___2'; did you mean '__builtin_va_list'?
  typedef __builtin_va_list___2 va_list___2;
          ^~~~~~~~~~~~~~~~~~~~~
          __builtin_va_list
  note: '__builtin_va_list' declared here
  In file included from skeleton/profiler.bpf.c:3:
  .../selftests/bpf/tools/build/bpftool/vmlinux.h:84050:9: error: unknown type name
       '__builtin_va_list__ _2'; did you mean '__builtin_va_list'?
  typedef __builtin_va_list___2 va_list___2;
          ^~~~~~~~~~~~~~~~~~~~~
          __builtin_va_list
  note: '__builtin_va_list' declared here

The error can be easily explained with after-dedup vmlinux btf:
  [21] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
  [2300] STRUCT '__va_list_tag' size=24 vlen=4
        'gp_offset' type_id=2 bits_offset=0
        'fp_offset' type_id=2 bits_offset=32
        'overflow_arg_area' type_id=32 bits_offset=64
        'reg_save_area' type_id=32 bits_offset=128
  [2308] TYPEDEF 'va_list' type_id=2309
  [2309] TYPEDEF '__builtin_va_list' type_id=2310
  [2310] ARRAY '(anon)' type_id=2300 index_type_id=21 nr_elems=1

  [5289] PTR '(anon)' type_id=2308
  [158520] STRUCT 'warn_args' size=32 vlen=2
        'fmt' type_id=14 bits_offset=0
        'args' type_id=2308 bits_offset=64
  [27299] INT '__ARRAY_SIZE_TYPE__' size=4 bits_offset=0 nr_bits=32 encoding=(none)
  [34590] TYPEDEF '__builtin_va_list' type_id=34591
  [34591] ARRAY '(anon)' type_id=2300 index_type_id=27299 nr_elems=1

Note that two array index_type_id's are different so the va_list and __builtin_va_list
will have two versions in the BTF. With this, vmlinux.h contains the following code,
  typedef __builtin_va_list va_list;
  typedef __builtin_va_list___2 va_list___2;
Since __builtin_va_list is a builtin type for the compiler,
libbpf does not generate
  typedef <...> __builtin_va_list
and this caused __builtin_va_list___2 is not defined and hence compilation error.
This happened when pahole is running with more than one jobs when parsing dwarf
and generating btfs.

Function btf_encoder__encode_cu() is used to do btf encoding for
each cu. The function will try to find an "int" type for the cu
if it is available, otherwise, it will create a special type
with name __ARRAY_SIZE_TYPE__. For example,
  file1: yes 'int' type
  file2: no 'int' type

In serial mode, file1 is processed first, followed by file2.
both will have 'int' type as the array index type since file2
will inherit the index type from file1.

In parallel mode though, arrays in file1 will have index type 'int',
and arrays in file2 wil have index type '__ARRAY_SIZE_TYPE__'.
This will prevent some legitimate dedup and may have generated
vmlinux.h having compilation error.

This patch fixed the issue by creating an 'int' type as the
array index type, so all array index type should be the same
for all cu's even in parallel mode.

Signed-off-by: Yonghong Song <yhs@fb.com>
Acked-by: Andrii Nakryiko <andrii@kernel.org>
Cc: Alexei Starovoitov <ast@kernel.org>
Cc: Daniel Borkmann <daniel@iogearbox.net>
Cc: bpf@vger.kernel.org
Cc: dwarves@vger.kernel.org
Cc: kernel-team@fb.com
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>