dwarf_loader: Fix array overrun access
Fixing this coverity report:

  Error: OVERRUN (CWE-119): [#def7]
  dwarves-1.13/dwarf_loader.c:54: cond_at_most: Checking "tag < DW_TAG_MIPS_loop" implies that "tag" may be up to 16512 on the true branch.
  dwarves-1.13/dwarf_loader.c:55: overrun-local: Overrunning array "dwarf_tags_warned" of 66 bytes at byte offset 16512 using index "tag" (which evaluates to 16512).
  #   53|
  #   54|   	if (tag < DW_TAG_MIPS_loop) {
  #   55|-> 		if (dwarf_tags_warned[tag])
  #   56|   			return;
  #   57|   		dwarf_tags_warned[tag] = true;

Reported-by: William Cohen <wcohen@redhat.com>
Fixes: c7fa6a9a401e ("dwarf loader: Catch some more template tags")
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>