codiff: Remove unused filenames variable
I changed the logic at some point stopping the use of that variable, but
then forgot to remove it, do it now.

Addresses this coverity report entry:

  Error: COMPILER_WARNING: [#def3]
  dwarves-1.13/codiff.c: scope_hint: In function 'main'
  dwarves-1.13/codiff.c:776:8: warning: variable 'filenames' set but not used [-Wunused-but-set-variable]
  #  776 |  char *filenames[2];
  #      |        ^~~~~~~~~
  #  774|   	int remaining, err, rc = EXIT_FAILURE;
  #  775|   	char *old_filename, *new_filename;
  #  776|-> 	char *filenames[2];
  #  777|   	struct stat st;
  #  778|

Need to find how to make cmake show these warnings...

Reported-by: William Cohen <wcohen@redhat.com>
Fixes: 991c6a3ebb5d ("dwarves: Rename cus__loadfl with cus__load_files")
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>