elfcreator: Remove unused 'machine' variable
Addresses:

  [ 84%] Building C object CMakeFiles/scncopy.dir/elfcreator.c.o
  /home/acme/git/pahole/elfcreator.c: In function ‘elfcreator_begin’:
  /home/acme/git/pahole/elfcreator.c:57:12: error: variable ‘machine’ set but not used [-Werror=unused-but-set-variable]
    GElf_Half machine;
              ^~~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>