dwarf_loader: Check tag__recode_dwarf_bitfield() return, may be NULL
Found by covscan:

  Error: GCC_ANALYZER_WARNING (CWE-476):
  dwarves-1.21/dwarf_loader.c:718:29: warning[-Wanalyzer-null-dereference]: dereference of NULL 'dtype'
  #  716|                 struct dwarf_tag *dtype = dwarf_cu__find_type_by_ref(cu->priv,
  #  717|                                                                      &dtag->type);
  #  718|->               struct tag *type = dtype->tag;
  #  719|
  #  720|                 id = tag__recode_dwarf_bitfield(type, cu, bit_size);

  Error: GCC_ANALYZER_WARNING (CWE-476):
  dwarves-1.21/dwarf_loader.c:740:29: warning[-Wanalyzer-null-dereference]: dereference of NULL 'dtype'
  #  738|                 const struct dwarf_tag *dtag = tag->priv;
  #  739|                 struct dwarf_tag *dtype = dwarf_cu__find_type_by_ref(cu->priv, &dtag->type);
  #  740|->               struct tag *type = dtype->tag;
  #  741|
  #  742|                 id = tag__recode_dwarf_bitfield(type, cu, bit_size);

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>